version: "3.8"

services:
  db_inventario:
    image: mysql:8.0
    container_name: inventario_mysql_compose
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: inventario_db
    ports:
      - "3308:3306"
    volumes:
      - inventario_db_data:/var/lib/mysql
    networks:
      - inventario_network_compose

  app_inventario:
    build:
      context: .
      dockerfile: Dockerfile
    image: inventario-app-compose:1.0.0
    container_name: inventario_app_compose
    depends_on:
      - db_inventario
    restart: always
    ports:
      - "8082:8080"
    networks:
      - inventario_network_compose

volumes:
  inventario_db_data:

networks:
  inventario_network_compose:
    name: inventario_network_compose
