apiVersion: v1
kind: Service
metadata:
  name: inventario-app-service
spec:
  type: LoadBalancer  # Cambia a NodePort si no usarás minikube tunnel
  selector:
    app: inventario-app
  ports:
    - port: 8080
      targetPort: 8080
